// Generated by Xata Codegen 0.30.1. Please do not edit.
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from '@xata.io/client';
import { buildClient } from '@xata.io/client';

const tables = [
  {
    name: 'test',
    checkConstraints: {
      test_xata_id_length_xata_id: {
        name: 'test_xata_id_length_xata_id',
        columns: ['xata_id'],
        definition: 'CHECK ((length(xata_id) < 256))',
      },
    },
    foreignKeys: {},
    primaryKey: [],
    uniqueConstraints: {
      _pgroll_new_test_xata_id_key: {
        name: '_pgroll_new_test_xata_id_key',
        columns: ['xata_id'],
      },
    },
    columns: [
      {
        name: 'xata_createdat',
        type: 'datetime',
        notNull: true,
        unique: false,
        defaultValue: 'now()',
        comment: '',
      },
      {
        name: 'xata_id',
        type: 'text',
        notNull: true,
        unique: true,
        defaultValue: "('rec_'::text || (xata_private.xid())::text)",
        comment: '',
      },
      {
        name: 'xata_updatedat',
        type: 'datetime',
        notNull: true,
        unique: false,
        defaultValue: 'now()',
        comment: '',
      },
      {
        name: 'xata_version',
        type: 'int',
        notNull: true,
        unique: false,
        defaultValue: '0',
        comment: '',
      },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Test = InferredTypes['test'];
export type TestRecord = Test & XataRecord;

export type DatabaseSchema = {
  test: TestRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    'https://Francis-Frias-s-workspace-smfut0.ap-southeast-2.xata.sh/db/Demo-Application',
  apiKey: process.env.XATA_API_KEY,
  branch: 'main',
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
